env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
plugins:
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
 no-param-reassign: 0
 prettier/prettier: error
 no-console: 0
 # TODO: This should really be error
 no-unused-vars: warn
 no-empty: warn
 quotes:
  - warn
  - single
  - avoidEscape: true
