
image: node:8-alpine

stages:
  - prepare
  - test

node_modules:
  stage: prepare
  artifacts:
    paths:
      - node_modules
  script:
    - yarn install

lint:
  stage: test
  allow_failure: true
  script:
    - yarn lint
